"""
Sprint G: POLLIT/POLNON Regression Tests.

Scaffold generated by Gemini CLI (Task 19), validated and corrected by Claude Code.
Import fix: JobInput is in abc_engine.py, not models.py.
"""
import pytest
from abc_engine import estimate_pylon, SignType, JobInput


def _pylon_job(sf, height, illuminated=True, num_faces=2, has_vinyl=True, footing=True):
    """Helper to create a JobInput for Pylon tests."""
    return JobInput(
        sign_type=SignType.POLLIT if illuminated else SignType.POLNON,
        sign_sf_per_face=sf,
        num_faces=num_faces,
        is_illuminated=illuminated,
        has_vinyl=has_vinyl,
        has_structural_steel=True,
        has_footing=footing,
        install_height_ft=height,
        miles_one_way=25.0,
        crew_size=3,
    )


class TestPylonRegression:
    """
    Sprint G: Regression coverage for Pylon (POLLIT/POLNON).
    10+ test cases across size and height ranges.
    """

    @pytest.mark.timeout(30)
    @pytest.mark.parametrize("sf, height", [
        (24.0, 15.0),  # Small
        (48.0, 25.0),  # Medium
        (96.0, 40.0),  # Large
    ])
    def test_pollit_standard_ranges(self, sf, height):
        """Verify standard illuminated pylon ranges."""
        job = _pylon_job(sf, height, illuminated=True)
        result = estimate_pylon(job)
        assert result.total_man_hours > 0

    @pytest.mark.timeout(30)
    @pytest.mark.parametrize("sf, height", [
        (24.0, 15.0),
        (48.0, 25.0),
        (96.0, 40.0),
    ])
    def test_polnon_standard_ranges(self, sf, height):
        """Verify standard non-illuminated pylon ranges."""
        job = _pylon_job(sf, height, illuminated=False)
        result = estimate_pylon(job)
        assert result.total_man_hours > 0

    def test_pollit_has_electrical(self):
        """POLLIT must include 0340 Electrical Wiring."""
        job = _pylon_job(48.0, 25.0, illuminated=True)
        result = estimate_pylon(job)
        all_lines = result.labor_lines + result.install_lines
        assert any(line.work_code == "0340" for line in all_lines), \
            "POLLIT must have 0340 Electrical"

    def test_polnon_no_electrical(self):
        """POLNON must NOT include 0340 Electrical Wiring."""
        job = _pylon_job(48.0, 25.0, illuminated=False)
        result = estimate_pylon(job)
        all_lines = result.labor_lines + result.install_lines
        assert not any(line.work_code == "0340" for line in all_lines), \
            "POLNON must NOT have 0340 Electrical"

    def test_pylon_minimum_sf(self):
        """Edge Case: Minimum surface area."""
        job = _pylon_job(1.0, 15.0)
        result = estimate_pylon(job)
        assert result.total_man_hours > 0

    def test_pylon_extreme_height(self):
        """Edge Case: Very tall pylon (100ft)."""
        job = _pylon_job(48.0, 100.0)
        result = estimate_pylon(job)
        assert result.total_man_hours > 0

    def test_pylon_single_face_vs_double(self):
        """Logic: Single face should be cheaper than double face."""
        sf, h = 48.0, 25.0
        sf_res = estimate_pylon(_pylon_job(sf, h, num_faces=1))
        df_res = estimate_pylon(_pylon_job(sf, h, num_faces=2))
        assert sf_res.total_man_hours < df_res.total_man_hours

    def test_pylon_footing_exclusion(self):
        """Verify that excluding footing removes 0605 labor."""
        with_footing = estimate_pylon(_pylon_job(48.0, 25.0, footing=True))
        without_footing = estimate_pylon(_pylon_job(48.0, 25.0, footing=False))
        footing_lines_with = [
            l for l in with_footing.labor_lines + with_footing.install_lines
            if l.work_code == "0605"
        ]
        footing_lines_without = [
            l for l in without_footing.labor_lines + without_footing.install_lines
            if l.work_code == "0605"
        ]
        # With footing should have 0605, without should not
        if footing_lines_with:
            assert len(footing_lines_without) == 0, \
                "Excluded footing should not have 0605"

    def test_pylon_vinyl_exclusion(self):
        """Verify that excluding vinyl removes vinyl labor codes."""
        with_vinyl = estimate_pylon(_pylon_job(48.0, 25.0, has_vinyl=True))
        without_vinyl = estimate_pylon(_pylon_job(48.0, 25.0, has_vinyl=False))
        vinyl_codes = {"0520", "0550"}
        vinyl_hrs_with = sum(
            l.hours for l in with_vinyl.labor_lines
            if l.work_code in vinyl_codes
        )
        vinyl_hrs_without = sum(
            l.hours for l in without_vinyl.labor_lines
            if l.work_code in vinyl_codes
        )
        assert vinyl_hrs_without < vinyl_hrs_with, \
            "Excluding vinyl should reduce vinyl labor"
